version: '3.8'

services:

  shiny-app2: # a dummy server for testing
    image: shinyapp2:latest
    build: 
      context: ./app2
      dockerfile: Dockerfile
    ports:
      - "3838:3838"
    volumes:
      - ./app2/app.R:/usr/src/app/app.R
    networks:
      - appnetwork
    restart: always


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"  # Add port for SSL
    volumes:
      - ${NGINX_CONF:-./nginx/nginx.conf}:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd-ortholog-seeker:/etc/nginx/.htpasswd-orthology-seeker:ro
      - ./nginx/.htpasswd-app2:/etc/nginx/.htpasswd-app2:ro
      - ./certbot/etc/letsencrypt:/etc/letsencrypt  # Mount Certbot configuration directory
      - ./certbot/www/:/var/www/letsencrypt
    depends_on:
      - shiny-app2
    networks:
      - appnetwork
    restart: always

  certbot:
    image: certbot/certbot:latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www/:/var/www/letsencrypt
      - ./certbot/log:/var/log/letsencrypt 
    networks:
      - appnetwork
    depends_on:
      - nginx
    restart: always

networks:
  appnetwork: