version: '3.8'

services:

  shiny-ortholog-seeker:
    image: ortholog-seeker:latest
    build: 
      context: ./Ortholog_Seeker
      dockerfile: Dockerfile
    networks:
      - appnetwork

  shiny-app1: # a dummy server for testing
    image: shinyapp1:latest
    build: 
      context: ./app1
      dockerfile: Dockerfile
    volumes:
      - ./app1/app.R:/usr/src/app/app.R
    networks:
      - appnetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"  # Add port for SSL
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd-ortholog-seeker:/etc/nginx/.htpasswd-orthology-seeker:ro
      - ./nginx/.htpasswd-app1:/etc/nginx/.htpasswd-app1:ro
      - certbot-etc:/etc/letsencrypt  # Mount Certbot configuration directory
    depends_on:
      - shiny-ortholog-seeker
      - shiny-app1
    networks:
      - appnetwork

  certbot:
    image: certbot/certbot:latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - certbot-etc:/etc/letsencrypt  # Mount Certbot configuration directory
      - /var/log/letsencrypt:/var/log/letsencrypt  # Mount log directory
    networks:
      - appnetwork

networks:
  appnetwork:

volumes:
  certbot-etc:
